version: '3.8'

services:
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER:-yaroute}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD:-yaroute}
      POSTGRES_DB: ${APP_DATABASE_NAME:-yaroute}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  rails:
    image: ${APP_IMAGE:-ghcr.io/kmmndr/yaroute:latest}
    restart: always
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      RAILS_ENV: ${PROJECT_ENVIRONMENT:-production}
      NODE_ENV: ${PROJECT_ENVIRONMENT:-production}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES:-0}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT:-}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-weak_secret_key}
      #
      DATABASE_URL: postgresql://${APP_DATABASE_USER:-yaroute}:${APP_DATABASE_PASSWORD:-yaroute}@postgres:5432/${APP_DATABASE_NAME:-yaroute}
      #
      PS1: "[$$RAILS_ENV] \\w \\$$ "
    depends_on:
      - postgres

volumes:
  postgres-data:
